### ISSUE TITLE
Support to SRP

### ISSUE THREAD

**Issue by ghost** [keijiro/KinoContour#7]
Primarily, it wasn't working but after some testing, I found out that the filter doesn't seem to work  with the SRP. It's understandable, support would be amazing tho.

**Comment by keijiro** [comment]
For SRPs, you can use Kino custom effects. Please see the following page.

https://github.com/keijiro/Kino

The Recolor effect works as an edge detection filter; You can use edge detection alone by disabling false color properties.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
